### ISSUE TITLE
Should staff be able to take quizzes made by other staff or just view them?

### ISSUE THREAD

**Issue by TwoRice** [jmsnll/QuizBiz#5]
Obviously staff should only be able to edit quizzes they have made.
But if a staff member selects a quiz made by another member of staff should it work as if a student had selected it (loading the Take Quiz) or should the staff just be able to view it the same as on the Edit Quiz page but without editing permissions?

Another extension to this could be allowing staff to give editing permissions to other members of staff which would have to be discussed with the client.

**Comment by dbrereton1995** [comment]
I think it'd be best if staff were only able to view quizzes created by other members of staff as it's there own intellectual property.

**Comment by zhaks** [comment]
Staff might want to test their own knowledge on other topics

**Comment by TwoRice** [comment]
I agree with db, I think staff would rather have more immediate access to the information.

**Comment by TwoRice** [comment]
After our scrum we have decided to just give staff a full view of the quiz when they view it but deny editing permissions
